[build]
  functions = "functions/"
  publish = "docs/"

[[plugins]]
  package = "netlify-plugin-form-submissions"

  [plugins.inputs]
    formNames = "sampleApprovedComments"
    dataDirectory = "comment/_data"
