[build]
  command = "yarn run build && hugo --gc --minify -b $URL"
  functions = "functions/"
  publish = ""

[[plugins]]
  package = "netlify-plugin-form-submissions"

  [plugins.inputs]
    formNames = "sampleApprovedComments"
    dataDirectory = "comment/_data"
